spring:
  datasource:
    username: curry
    password: Ocean1109
    url: jdbc:postgresql://152.136.110.205:8081/shopping
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #Redis配置
  redis:
    database: 0
    host: 140.143.242.142
    port: 6379
    timeout: 1000

server:
  port: 8181


# 阿里云存储参数配置
aliyun:
  oss:
    endpoint: 
    accessKeyId: 
    accessKeySecret: 
    bucketName: 

# 开启hystrix
feign:
  circuitbreaker:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://152.136.110.205:8000/eureka/,http://152.136.110.205:8001/eureka/,http://152.136.110.205:8002/eureka/


