spring:
  datasource:
    username: curry
    password: Ocean1109
    url: jdbc:postgresql://152.136.110.205:8081/shopping
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8181


# 阿里云存储参数配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5t6Ke7hnD9M1WF6bvhae
    accessKeySecret: MWA3UiU9i16kMj9bJWCOyaGOg8E5ik
    bucketName: ocean1109
